config/routes.rb
Rails.application.routes.draw do
  devise_for :editors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 root 'articles#index' 
 get 'home' => 'articles#index'
 
 resources :articles do 
 	collection do 
 		get :search 
 	end 
 end 

 get 'new-post' => 'articles#new'
 resources :subscribers  
 get 'newsletter' => 'subscribers#new'

 get 'music' => 'pages#index_music'
 get 'cinema' => 'pages#index_cinema'
 get 'books' => 'pages#index_books'
 get 'culinary-art' => 'pages#index_food'
 get 'brands' => 'pages#index_brand'
 get 'events' => 'pages#index_event'
 get 'latest' => 'pages#app_index'

 delete 'logout' => 'devise/registrations#destroy' 

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

	has_attached_file :image, styles: { large: "600x600>", thumb: "300x300>" }
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

	def self.search(search)
		where('category LIKE ? OR title LIKE ? OR description LIKE ? OR author LIKE ? OR body LIKE ?', "%#{search}%","%#{search}%", "%#{search}%","%#{search}%", "%#{search}%")
	end 
 
end

app/models/editor.rb
class Editor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  def admin?
    self.role == 'Admin'
  end 

end

app/models/subscriber.rb
class Subscriber < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

before_action :set_subscriber 

def require_admin 
    redirect_to '/' unless current_editor.admin?
end 


private 
def set_subscriber
	@subscriber = Subscriber.new 
end 

end 

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_action :authenticate_editor!, except: [:index, :show]

	before_action :require_admin, only: [:destroy]

	def index 
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 7)
	end 

	def search
		if params[:search]
  			@articles = Article.search(params[:search]).order(created_at: :desc).paginate(:page => params[:page], :per_page => 9)
  		else
    		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 7) 
  		end
	end 

	def new  
		@article = Article.new 
	end 

	def create 
		@article = Article.new(article_params)
			if @article.save 
				redirect_to '/home'
			else 
				render 'new'
		end 
	end 

	def show 
		@article = Article.find(params[:id]) 
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 4)
	end

	def edit 
		@article = Article.find(params[:id]) 
	end 

	def update 
		@article = Article.find(params[:id]) 

		if @article.update(article_params) 
			redirect_to @article
		else 
			render 'edit'
		end 
	end 

	def destroy 
		@article = Article.find(params[:id]) 
		@article.destroy 
		redirect_to '/home'
	end 

	private 
	def article_params
		params.require(:article).permit(:title, :description, :image, :author, :body, :category) 
	end 

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index_music
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def index_cinema
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def index_books
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def index_food
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def index_brand
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def index_event
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 9)
	end 

	def app_index
		@articles = Article.order(created_at: :desc).all.paginate(:page => params[:page], :per_page => 7)
	end 

end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController

  def new 
  	@subscriber = Subscriber.new 
  end 

  def create 
	@subscriber = Subscriber.new(subscriber_params)
		if @subscriber.save 
			SubscriptionMailer.confirmation_email(@subscriber).deliver
			redirect_to '/'
		else 
			render 'new'
		end 
	end

	private 
	def subscriber_params 
		params.require(:subscriber).permit(:email) 
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/subsribers_helper.rb
module SubsribersHelper
end

app/views/articles/edit.html.erb
<div class="editor-form">
	<%= form_for @article, html: { multipart: true } do |f| %>
		<%= f.text_field :author, :value => @article.author %> 
		<%= f.text_field :title, :value => @article.title %>
		<%= f.text_field :category, :placeholder => 'category', :value => @article.category %>
		<%= f.text_field :description, :value => @article.description %>
		<%= f.file_field :image, :value => @article.image, :id => 'upload' %>
		<%= f.text_area :body, :value => @article.body, :id => 'body' %>
		<%= f.submit 'Edit', :id => "submit-new" %> 
	<% end %> 
</div> 

app/views/articles/index.html.erb
<% @articles.each do |article| %>
	<% if article == @articles.first %> 
		<%= link_to(article) do %>
			<div class="hero-wrapper">
				<div class="illustration">
					<%= image_tag article.image %> 
				</div>
				<div class="details">
					<p><span id="tag">Artsy</span><span id="categ"><%= article.category %></span></p> 
					<h1><%= article.title %></h1>
					<p id="description"><%= article.description %></p> 
				</div>
			</div>
		<% end %> 
	<% end %> 
<% end %>

<hr class="mobile-only">
 
<div class="title">
	<h6>Latest Picks</h6>
</div>

<div class="articles">
	<% @articles.each do |article| %>
		<% if article != @articles.first%> 
			<%= link_to(article) do %>
				<div class="article-wrapper">
					<div class='image'>
						<%= image_tag article.image %>
					</div>
					<p id="cat"><%= article.category %></p>
					<h1><%= article.title %></h1>
					<p><%= article.description %></p> 
				</div>
			<% end %> 
		<% end %>  
	<% end %> 
</div>

<div class="next">
	<button><%= link_to "More stories", latest_path %></button>
</div>

<div class="newsletter">
	<p>Join our weekly newsletter</p>
	<%= render 'subscribers/new' %>
</div>

app/views/articles/new.html.erb
<div class="editor-form">
	<%= form_for @article, html: { multipart: true } do |f| %>
		<%= f.text_field :author, :placeholder => 'author' %> 
		<%= f.text_field :title, :placeholder => 'title' %>
		<%= f.text_field :category, :placeholder => 'category' %>
		<%= f.text_field :description, :placeholder => 'description' %>
		<%= f.file_field :image, :placeholder => 'image', :id => 'upload' %>
		<%= f.text_area :body, :placeholder => 'body', :id => 'body' %>
		<%= f.submit 'Post', :id => "submit-new" %> 
	<% end %> 
</div> 

app/views/articles/search.html.erb
<div class="results-wrapper">
	<% @articles.each do |article| %> 
		<%= link_to(article) do %>
			<div class="result">
				<div class="pic">
					<%= image_tag article.image %>
				</div>
				<div class="card">
					<p><%= article.created_at.strftime('%b %d') %>, <%= article.created_at.strftime('%Y') %></p>
					<h1><%= article.title %></h1>
					<p><%= article.description %></p> 
				</div>
			</div>
		<% end %> 
	<% end %>
</div>

app/views/articles/show.html.erb
<div class="page-wrapper">
	<div class="post-wrapper">
		<div class="article-header">
			<h5><%= @article.category %></h5> 
			<h1><%= @article.title %></h1>
			<p>By <%= @article.author %>, <%= @article.created_at.strftime('%b %d') %>, <%= @article.created_at.strftime('%Y') %></p> 
		</div>
		<div class="article-image">
			<%= image_tag @article.image %>
		</div>
		<div class="article-body">
			<p style="white-space: pre-line;"><%= @article.body %></p>
		</div>
		<div class="editor-options">
			<% if editor_signed_in? && current_editor.role == 'Admin' %> 
			<ul>
				<li><%= link_to 'Edit', edit_article_path %></li>
				<li><%= link_to 'Delete', article_path, method: 'delete' %></li>
				<li><%= link_to 'New Article', new_post_path %></li>
			</ul>
			<% elsif editor_signed_in? %>
			<ul class="editor-options">
				<li><%= link_to 'Edit', edit_article_path %></li>
				<li><%= link_to 'New Article', new_post_path %></li>
			</ul> 
			<% end %>
		</div>
	</div>

	<div class="suggestions-wrapper">
		<div class="suggestions-title">
			<p>Discover</p>
		</div>
		<% @articles.each do |article| %>
		<div class="suggestion-wrapper">
		<div class="suggestion">
				<%= link_to(article) do %>
					<% if @article.id != article.id %>
						<div class="illu"> 
							<%= image_tag article.image %>
						</div>
						<p><%= article.title %></p> 
					<% end %> 
				<% end %> 
			</div>
			</div>
		<% end %> 
	</div>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheArtsy</title>
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700|Raleway:300,400,500" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://use.fontawesome.com/9c64063f1f.js"></script>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag :defaults %>
  </head>

  <body>

    <div class="search-modal">
      <div class="close">
        <i class="fa fa-times" aria-hidden="true"></i>
      </div>
      <div class="form-wrapper">
      <%= form_tag search_articles_path, :method => 'get' do %> 
        <%= text_field_tag :search, params[:search], :placeholder => "Search", :id => 'input', :autofocus => true %>
        <%= submit_tag " ", :id => "submit" %>
      <% end %>
      </div> 
    </div>

    <% if editor_signed_in? %>
    <div class="editor-signout">
          <p><%= link_to "Log out", destroy_editor_session_path, method: 'delete' %></p>
    </div>
    <% end %>

  	<div class="header">
  		<div class="header-wrapper">
  			<p><%= link_to "The Artsy", root_path %></p>
  			<i id="menu" class="fa fa-bars" aria-hidden="true"></i>
  		</div>
  	</div>

    <div class="mobile-nav">
        <ul>
          <li id="inline"><i id="search-mobile" class="fa fa-search" aria-hidden="true"></i> <%= form_tag search_articles_path, :method => 'get' do %> <%= text_field_tag :search, params[:search], :placeholder => "Search", :id => 'mobile' %></li>
          <li id="search-submit"><%= submit_tag " " %></li> <% end %>
          <li><%= link_to "Music", music_path %></li>
          <li><%= link_to "Cinema", cinema_path %></li>
          <li><%= link_to "Books", books_path %></li>
          <li><%= link_to "Culinary Art", culinary_art_path %></li>
          <li><%= link_to "Brands", brands_path %></li>
          <li><%= link_to "Events", events_path %></li>
        </ul>
      </div> 

  	<div class="navigation">
  		<ul>
  			<li><%= link_to "Music", music_path %></li>
  			<li><%= link_to "Cinema", cinema_path %></li>
  			<li><%= link_to "Books", books_path %></li>
  			<li><%= link_to "Culinary Art", culinary_art_path %></li>
  			<li><%= link_to "Brands", brands_path %></li>
  			<li><%= link_to "Events", events_path %></li>
        <li id="search"><i class="fa fa-search" aria-hidden="true"></i></li>
  		</ul>
    </div>

    <hr> 

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <div class="footer">
    	<div class="flex-wrapper">
    		<ul>
  				<li><%= link_to "Music", music_path %></li>
  				<li><%= link_to "Cinema", cinema_path %></li>
  				<li><%= link_to "Books", books_path %></li>
  				<li><%= link_to "Culinary Art", culinary_art_path %></li>
  				<li><%= link_to "Brands", brands_path %></li>
  				<li><%= link_to "Events", events_path %></li> 
  			</ul>
  		</div>
  		<div class="end">
  			<p>&copy; the Artsy 2016 all rights reserved</p> 
  		</div>
    </div>

  </body>
</html>

app/views/pages/app_index.html.erb
<div class="latest-header">
	<h1>Latest</h1>
</div>

<div class="latest-wrapper">
	<% @articles.each do |article| %>
		<div class="latest">
			<div class="img">
				<%= image_tag article.image %> 
			</div>
			<div class="info">
				<p><%= article.created_at.strftime('%b %d') %>, <%= article.created_at.strftime('%Y') %></p> 
				<h3><%= article.title %> </h3>
				<p id="author">By <%= article.author %></p> 
				<p><%= article.description %></p> 
			</div>
		</div>
	<% end %>
</div>

<div class="pages">
	<%= will_paginate @articles %>
</div> 

app/views/pages/index_books.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Books</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Books" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="dscription"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>


	<div class="right-wrapper">

	</div>
</div>

app/views/pages/index_brand.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Brands</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Brands" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="dscription"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>


	<div class="right-wrapper">

	</div>
</div>

app/views/pages/index_cinema.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Movies</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Movies" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="dscription"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>


	<div class="right-wrapper">

	</div>
</div>

app/views/pages/index_event.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Events</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Event" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="dscription"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>


	<div class="right-wrapper">

	</div>
</div>

app/views/pages/index_food.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Food</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Food" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="dscription"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>

	<div class="right-wrapper">

	</div>
</div>

app/views/pages/index_music.html.erb
<div class="intro">
	<h1><span id="serif">Artsy</span><span>Music</span></h1>
</div>

<div class="category-wrapper">
	<div class="left-wrapper">
		<% @articles.each do |article| %> 
				<% if article.category == "Music" %>
					<%= link_to(article) do %> 
						<div class="article">
							<div class="image">
								<%= image_tag article.image %>
							</div> 
							<div class="details">
								<p id="author">By <%= article.author %></p> 
								<p id="title"><%= article.title %></p> 
								<p id="brief"><%= article.description %></p>
							</div> 
						</div> 
				<% end %> 
			 <% end %> 
		<% end %> 
	</div>


	<div class="right-wrapper">

	</div>
</div>

app/views/subscribers/_new.html.erb
<%= form_for(@subscriber) do |f| %> 
    <%= f.email_field :email, :placeholder => "email address", :id => "email" %> 
    <%= f.submit 'Sign up', :id => "singup" %> 
<% end %>